services:
  symfony-db:
    container_name: symfony-db
    image:  mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  symfony-php:
    container_name: symfony-php
    build:
      context: ./containers/php
    ports:
      - '9000:9000'
    volumes:
      - ./volumes/php:/var/www/symfony_docker
      - ./containers/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - symfony-db



  symfony-nginx:
    container_name: symfony-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./volumes/php:/var/www/symfony_docker
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony-php
      - symfony-db
      - symfony-node